### ISSUE TITLE
VARCHAR requires a length on dialect mysql

### ISSUE THREAD

**Issue by Stiivi** [Stiivi/brewery#11]
SQLTableDataTarget requires fix for the error: "VARCHAR requires a length on dialect mysql".

Possible solutions:
- add "size" to the type metadata
- if there is no size, use some default value (this should be backend dependent - which is not very nice/clean)

**Comment by Stiivi** [comment]
See SQL Alchemy [custom types](http://docs.sqlalchemy.org/en/rel_0_7/core/compiler.html#changing-compilation-of-types) for more information of possible (partial) implementation.

**Comment by jjmontesl** [comment]
Are there any news? I'm trying to use concrete_storage_type="VARCHAR(250)"  but doesn't seem to work

**Comment by jjmontesl** [comment]
Have a look at https://github.com/jjmontesl/brewery/commit/5538dd85cbce94d40e2bf290a54204981ddb4f33 ?

That enforces a 128 character default, though.

**Comment by Stiivi** [comment]
added this to the new etl branch, except the 128 character length. You can now handle it only by passing `concrete_type_map` dictionary to the `SQLDataStore` or by specifying `field.size` ("size" was chosen as more generic version of this property, like it might be a list of array dimensions not only scalar representing length).

**Comment by Stiivi** [comment]
Added default string length, handled on dialect basis, currently only mysql in there as it is the only known offending. In branch etl, not main.
